<div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	
	<?php #get subscriptioninfo  from function defined in block ?>
	<?php $subsCollection = $this->getSubscriptions(); ?>
	
	<?php #get vendorid from function defined in block ?>
	<?php $vendorId =$this->vendorId();  ?>
	<h2 style="margin-top:10px;">Select Plan</h2>
    <?php  foreach($subsCollection as $subsCollections){ ?>
	   <input type="radio" name="radio" value="<?php echo $subsCollections['id']  ?>" onclick="check(this);" />	
	   <?php echo  $subsCollections['subsname'];?>@<?php echo  $subsCollections['amout']."$";?>
       <br />
   <?php }  ?> 
</div> 

<h2 style="margin-top:10px;">Select Payment Methoed To Pay</h2>
 <!--<div id="paypal">  
    <input type="radio" id="paypal" name="payment_type" value="paypal" />
    <span id="paypala">Paypal standard</span> 
	<div style="display:none" id="ppal">  
			
			<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" >
			<input type="hidden"  value="_xclick" name="cmd">
			<input type="hidden"  value="2" name="rm">
			<input type="hidden"  value="testin_1282914921_biz@gmail.com" name="business">
			<input type="hidden"  value="http://localhost/vendors/index.php/vregistration/index/payment/" name="return">
			<input type="hidden"  value="http://deftsoft.info/property/properties/imagesResponse" name="notify_url">
			<input type="hidden"  value="USD" name="currency_code">
			<input type="hidden"  value="id" name="on0">
			<input type="hidden"  value="<?php echo $vendorId; ?>" name="os0">
			<input type="image" name="submit" src="http://www.paypal.com/en_US/i/btn/x-click-but6.gif" alt="Click to pay with PayPal - it is fast, free and secure!" />
			</form>
 	</div>
</div>-->

  <div id="paypal">  
    <input type="radio" id="ogone" name="payment_type" value="ogone" />
    <span id="ogonea">OGONE PAYMENT GATEWAY</span> 
	<div style="display:none" id="ogne">  
			<form action="" method="post" >
			 <b>Ogone payment area</b>
			</form>
 	 </div>
 </div>


<div id="direct">
	 <input type="radio"  value="credit" id="credit" name="payment_type">
	 <span id="credita">CREDIT CARD(paypal)</span>
	 <div style="display:none;" id="cardcredit">
					
				 <form action="<?php echo Mage::getUrl('vcatalog/paypal/getResponse') ?>" method="post" name="credeb" id="credeb"> 	
					<input type="hidden" name="payment[vid]" value="<?php  echo  $vendorId; ?>" />
					<input type="hidden" id="subsid" name="payment[subsid]" value="8" />
					
					<ul style="" id="payment_form_ccsave" class="form-list">
					<li>
					<label class="required" for="ccsave_cc_owner"><em>*</em>Name on Card</label>
					<div class="input-box">
					<input type="text" value="" name="payment[cc_owner]" id="ccsave_cc_owner" class="input-text required-entry" title="Name on Card" autocomplete="off">
					</div>
					</li>
					<li>
					<label class="required" for="ccsave_cc_type"><em>*</em>Credit Card Type</label>
					<div class="input-box">
					<select class="required-entry validate-cc-type-select" title="Credit Card Type" name="payment[cc_type]" id="ccsave_cc_type" autocomplete="off">
					<option value="">--Please Select--</option>
					<option value="AE">American Express</option>
					<option value="VI">Visa</option>
					<option value="MC">MasterCard</option>
					<option value="DI">Discover</option>
					</select>
					</div>
					</li>
					<li>
					<label class="required" for="ccsave_cc_number"><em>*</em>Credit Card Number</label>
					<div class="input-box">
					<input type="text" value="" class="input-text validate-cc-number validate-cc-type" title="Credit Card Number" name="payment[cc_number]" id="ccsave_cc_number" autocomplete="off">
					</div>
					</li>
					<li>
					<label class="required" for="ccsave_expiration"><em>*</em>Expiration Date</label>
					<div class="input-box">
					<div class="v-fix">
					<select class="month validate-cc-exp required-entry" name="payment[cc_exp_month]" id="ccsave_expiration" autocomplete="off">
					<option selected="selected" value="">Month</option>
					<option value="1">01 - January</option>
					<option value="2">02 - February</option>
					<option value="3">03 - March</option>
					<option value="4">04 - April</option>
					<option value="5">05 - May</option>
					<option value="6">06 - June</option>
					<option value="7">07 - July</option>
					<option value="8">08 - August</option>
					<option value="9">09 - September</option>
					<option value="10">10 - October</option>
					<option value="11">11 - November</option>
					<option value="12">12 - December</option>
					</select>
					</div>
					<div class="v-fix">
					<select class="year required-entry" name="payment[cc_exp_year]" id="ccsave_expiration_yr" autocomplete="off">
					<option selected="selected" value="">Year</option>
					<option value="2012">2012</option>
					<option value="2013">2013</option>
					<option value="2014">2014</option>
					<option value="2015">2015</option>
					<option value="2016">2016</option>
					<option value="2017">2017</option>
					<option value="2018">2018</option>
					<option value="2019">2019</option>
					<option value="2020">2020</option>
					<option value="2021">2021</option>
					<option value="2022">2022</option>
					</select>
					</div>
					</div>
					</li>
					<li>
					<label class="required" for="ccsave_cc_cid"><em>*</em>Card Verification Number</label>
					<div class="input-box">
					<div class="v-fix">
					<input type="text" value="" name="payment[cc_cid]" id="ccsave_cc_cid" class="input-text cvv required-entry validate-cc-cvn" title="Card Verification Number" autocomplete="off">
					</div>
					<a class="cvv-what-is-this" href="#">What is this?</a>
					</div>
					</li>
				</ul>
		<button type="submit" title="Submit" class="button validation-passed"><span><span>Submit</span></span></button>
	   </form>
	 </div>
	
</div>
<script type="text/javascript">
//< ![CDATA[
var customForm = new VarienForm('credeb');
//]]>
</script>
<script type="text/javascript">
//< ![CDATA[
Event.observe(window, 'load' ,function(){
Event.observe('ogone', 'click' , function(){
$('ogne').show();
$('cardcredit').hide();
});
Event.observe('credit', 'click' , function(){
$('cardcredit').show();
$('ogne').hide();
 });
});
//]]>
</script>
<script>
function check(getParams)
 {
   document.getElementById('subsid').value=getParams.value; 
  }
</script>
